server:
  port: 8000

# show full health details at /health
endpoints:
  health:
    sensitive: false

spring:
  cloud:
    config:
      server:
        native:
          search-locations: tmsc-config
        git:
          uri: https://github.com/Komdosh/TenMinutesCloudStreaming
          searchPaths: tmsc-config
