server:
  port: 8001

spring:
  devtools:
    livereload:
      port: 35731

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    wait-time-in-ms-when-sync-empty: 0
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
